name: build-container

on:
  push:
    branches:
      - master
  pull_request:

# permissions:
#   pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
