name: build-container

on:
  push:
    branches:
      - master
  pull_request:

# permissions:
#   pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      -
        name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # tags: hsoftware/isp-net-adminator:latest
