name: CI

on:
  push:
    branches:
      - master
  pull_request:

defaults:
 run:
  working-directory: ./adminator3

jobs:
  basic-checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-versions: ['8.2']

    name: Test on ${{ matrix.os }} with PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Print PHP version
        run: echo ${{ steps.setup-php.outputs.php-version }}

      - name: Install dependencies
        run: composer install --ignore-platform-reqs

      # - name: Run the tests
      #   run: composer phpunit

      - name: PHP CodeSniffer
        run: |
          composer \
          run \
            phpcs \
              app \
              boostrap \
              print \
              rss
            
      - name: PHP-CS-Fixer
        run: |
          php \
          vendor/friendsofphp/php-cs-fixer/php-cs-fixer \
          check \
          --show-progress=dots \
          -v

